<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-BlazorApp2-e83a9a99-be9a-44f6-84e2-adfb4c3c0d20</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <None Update="Data\app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.25"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.25"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.25"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.25"/>
    </ItemGroup>

</Project>
